# Generated by Django 5.1.1 on 2024-10-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='image_url',
        ),
    ]
